spring:
  application:
    name: fitness-tracker

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    com.pranav244872.fitness_tracker: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} - %msg%n"
